### ISSUE TITLE
CSS not included in npm run build command with Netlify

### ISSUE THREAD

**Issue by miteybig** [5t3ph/11ty-sass-skeleton#2]
Hello Stephanie.

Thank you so much for the starter skeleton. It's been a huge time-saver in my workflow.
So I've cloned this repo and have set-up continuous deployment with Netlify.
Here are the results: <https://xenodochial-torvalds-8aa5b9.netlify.app>

Here is a screenshot of my Netlify configuration (which I hope is correct):
![Screenshot_2020-10-18 Create a new site Netlify](https://user-images.githubusercontent.com/28819652/96753150-0d5a2b00-1395-11eb-87b5-6b6bd7457182.png)

It doesn't appear your base CSS styles—typography and background color are being referenced.
So—I hope you can help a total noob out.

Thank you so much.

**Comment by 5t3ph** [comment]
@miteybig you are totally right, the build order was causing this to fail. I had made an improvement on another project and so I've moved the changes here as well - you can update from this repo if you made a fork, or manually move the changes as shown here: https://github.com/5t3ph/11ty-sass-skeleton/commit/a3c42682ae96259e831152734746fc10195dd806
