### ISSUE TITLE
Multi layer folders sass

### ISSUE THREAD

**Issue by MedBilelAbidi** [5t3ph/11ty-sass-skeleton#4]
hello 

great work i really love it and help me but i have a question how can i complie scss file that exist in multi folder layers 
![image](https://user-images.githubusercontent.com/102331552/191294317-a2c1512c-62b8-45a9-baf9-51683ccc254c.png)
for exemple i want to compile buttons.scss that exist in sass/ui/elements/buttons.scss

**Comment by Guirdo** [comment]
In your `style.scss` use `@use './ui/elements/buttons'` and that should work

**Comment by 5t3ph** [comment]
@MedBilelAbidi - hopefully you got this figured out, standard Sass file patterns will work, there's nothing in-between!
